variable "project_name" {}
variable "region" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "ami_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "ecr_repository_url" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "admin_email" {}